cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'atuin'
brew 'cloudflared'
brew 'holman/tap/deckk'
brew 'imagemagick'
brew 'postgresql@17'
brew 'redis'
brew 'spaceman-diff'
brew 'spark'
brew 'wget'
brew 'yt-dlp'

cask '1password'
cask 'chatgpt'
cask 'codex'
cask 'ghostty'
cask 'iina'
cask 'zoom'
