cask_args appdir: '/Applications'

brew 'atuin'
brew 'blueutil'
brew 'btop'
brew 'cloudflared'
brew 'fastfetch'
brew 'imagemagick'
brew 'macmon'
brew 'postgresql@17'
brew 'redis'
brew 'spaceman-diff'
brew 'starship'
brew 'thefuck'
brew 'tmux'
brew 'tree'
brew 'wget'

# Casks
cask '1password'
cask 'aerospace'
cask 'antigravity-cli'
cask 'chatgpt'
cask 'codex'
cask 'dropbox'
cask 'ghostty'
cask 'iina'
cask 'inkscape'
cask 'karabiner-elements'
cask 'maccy'
cask 'zoom'
